/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "primary": "#000000",
          "primary-container": "#161a33",
          "surface-container-low": "#f2f4f6",
          "on-primary-fixed": "#161a33",
          "on-secondary-fixed-variant": "#004395",
          "surface-dim": "#d8dadc",
          "surface-bright": "#f7f9fb",
          "on-primary": "#ffffff",
          "on-error": "#ffffff",
          "inverse-surface": "#2d3133",
          "outline-variant": "#c7c5ce",
          "on-tertiary-fixed": "#23005c",
          "background": "#f7f9fb",
          "primary-fixed-dim": "#c1c4e6",
          "surface-container-high": "#e6e8ea",
          "outline": "#77767e",
          "on-tertiary-fixed-variant": "#5516be",
          "surface-container": "#eceef0",
          "on-error-container": "#93000a",
          "on-tertiary-container": "#9466ff",
          "surface-container-highest": "#e0e3e5",
          "on-surface-variant": "#46464d",
          "error": "#ba1a1a",
          "on-background": "#191c1e",
          "on-secondary": "#ffffff",
          "tertiary": "#000000",
          "tertiary-container": "#23005c",
          "tertiary-fixed-dim": "#d0bcff",
          "primary-fixed": "#dee0ff",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed-dim": "#adc6ff",
          "secondary": "#0058be",
          "on-primary-container": "#7e82a1",
          "surface-variant": "#e0e3e5",
          "tertiary-fixed": "#e9ddff",
          "on-primary-fixed-variant": "#414561",
          "on-secondary-fixed": "#001a42",
          "surface": "#f7f9fb",
          "secondary-container": "#2170e4",
          "on-surface": "#191c1e",
          "on-secondary-container": "#fefcff",
          "surface-tint": "#595c79",
          "inverse-primary": "#c1c4e6",
          "inverse-on-surface": "#eff1f3",
          "on-tertiary": "#ffffff",
          "error-container": "#ffdad6",
          "secondary-fixed": "#d8e2ff",
          "safepulse": {
              "dark": '#0f172a',      
              "card": '#1e293b',      
              "accent": '#10b981',    
              "danger": '#ef4444',    
              "warning": '#f59e0b',   
          }
      },
      "borderRadius": {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      "spacing": {
          "container-margin": "24px",
          "section-gap": "64px",
          "gutter": "16px",
          "stack-sm": "8px",
          "stack-md": "16px",
          "stack-lg": "32px",
          "base": "8px"
      },
      "fontFamily": {
          "label-sm": ["Inter"],
          "body-md": ["Inter"],
          "label-md": ["Inter"],
          "headline-md": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "headline-lg": ["Inter"],
          "body-lg": ["Inter"],
          "display-lg": ["Inter"]
      },
      "fontSize": {
          "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "headline-lg-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      },
      "animation": {
        'pulse-sos': 'pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slideUp 0.3s ease-out',
      }
    },
  },
  plugins: [],
}
